"""create raw and curated tables

Revision ID: 20260805_0001
Revises:
Create Date: 2026-08-05 22:14:19.196723
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260805_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS curated")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("key"),
        schema="curated",
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("customer_unique_id", sa.String(), nullable=False),
        sa.Column("zip_code_prefix", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("customer_id"),
        schema="curated",
    )
    op.create_index(
        "ix_customers_unique_id",
        "customers",
        ["customer_unique_id"],
        unique=False,
        schema="curated",
    )
    op.create_table(
        "data_refresh_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rows_affected", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="curated",
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=True),
        sa.Column("category_name_english", sa.String(), nullable=True),
        sa.Column("weight_g", sa.Numeric(), nullable=True),
        sa.Column("length_cm", sa.Numeric(), nullable=True),
        sa.Column("height_cm", sa.Numeric(), nullable=True),
        sa.Column("width_cm", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("product_id"),
        schema="curated",
    )
    op.create_table(
        "sellers",
        sa.Column("seller_id", sa.String(), nullable=False),
        sa.Column("zip_code_prefix", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("seller_id"),
        schema="curated",
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column(
            "role", sa.String(), server_default=sa.text("'analyst'"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        schema="curated",
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("order_status", sa.String(), nullable=False),
        sa.Column("purchase_ts", sa.DateTime(), nullable=False),
        sa.Column("approved_ts", sa.DateTime(), nullable=True),
        sa.Column("delivered_carrier_ts", sa.DateTime(), nullable=True),
        sa.Column("delivered_customer_ts", sa.DateTime(), nullable=True),
        sa.Column("estimated_delivery_ts", sa.DateTime(), nullable=True),
        sa.Column("is_late", sa.Boolean(), nullable=True),
        sa.Column("delivery_days", sa.Integer(), nullable=True),
        sa.Column("delivery_delay_days", sa.Integer(), nullable=True),
        sa.Column("is_delivery_days_outlier", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["curated.customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
        schema="curated",
    )
    op.create_index(
        "ix_orders_customer", "orders", ["customer_id"], unique=False, schema="curated"
    )
    op.create_index(
        "ix_orders_purchase_ts",
        "orders",
        ["purchase_ts"],
        unique=False,
        schema="curated",
    )
    op.create_index(
        "ix_orders_status", "orders", ["order_status"], unique=False, schema="curated"
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["curated.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("token_hash"),
        schema="curated",
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("order_item_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("seller_id", sa.String(), nullable=False),
        sa.Column("shipping_limit_date", sa.DateTime(), nullable=True),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("freight_value", sa.Numeric(), nullable=False),
        sa.Column(
            "is_price_outlier",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_freight_value_outlier",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["curated.orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["curated.products.product_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["curated.sellers.seller_id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "order_item_id"),
        schema="curated",
    )
    op.create_table(
        "payment_details",
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("payment_sequential", sa.Integer(), nullable=False),
        sa.Column("payment_type", sa.String(), nullable=False),
        sa.Column("payment_installments", sa.Integer(), nullable=True),
        sa.Column("payment_value", sa.Numeric(), nullable=False),
        sa.Column(
            "is_payment_value_outlier",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["curated.orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "payment_sequential"),
        schema="curated",
    )
    op.create_table(
        "payment_summary",
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("primary_payment_type", sa.String(), nullable=True),
        sa.Column("installments_max", sa.Integer(), nullable=True),
        sa.Column("total_payment_value", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["curated.orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
        schema="curated",
    )
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("review_score", sa.SmallInteger(), nullable=False),
        sa.Column("comment_title", sa.Text(), nullable=True),
        sa.Column("comment_message", sa.Text(), nullable=True),
        sa.Column("review_creation_ts", sa.DateTime(), nullable=True),
        sa.Column("review_answer_ts", sa.DateTime(), nullable=True),
        sa.CheckConstraint("review_score BETWEEN 1 AND 5", name="ck_review_score"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["curated.orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("review_id", "order_id"),
        schema="curated",
    )
    op.create_index(
        "ix_reviews_review_id", "reviews", ["review_id"], unique=False, schema="curated"
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column("customer_unique_id", sa.String(), nullable=True),
        sa.Column("customer_zip_code_prefix", sa.String(), nullable=True),
        sa.Column("customer_city", sa.String(), nullable=True),
        sa.Column("customer_state", sa.String(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "geolocation",
        sa.Column("geolocation_zip_code_prefix", sa.String(), nullable=True),
        sa.Column("geolocation_lat", sa.Numeric(), nullable=True),
        sa.Column("geolocation_lng", sa.Numeric(), nullable=True),
        sa.Column("geolocation_city", sa.String(), nullable=True),
        sa.Column("geolocation_state", sa.String(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("order_item_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("shipping_limit_date", sa.DateTime(), nullable=True),
        sa.Column("price", sa.Numeric(), nullable=True),
        sa.Column("freight_value", sa.Numeric(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "order_payments",
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("payment_sequential", sa.Integer(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("payment_installments", sa.Integer(), nullable=True),
        sa.Column("payment_value", sa.Numeric(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "order_reviews",
        sa.Column("review_id", sa.String(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("review_score", sa.Integer(), nullable=True),
        sa.Column("review_comment_title", sa.Text(), nullable=True),
        sa.Column("review_comment_message", sa.Text(), nullable=True),
        sa.Column("review_creation_date", sa.DateTime(), nullable=True),
        sa.Column("review_answer_timestamp", sa.DateTime(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column("order_status", sa.String(), nullable=True),
        sa.Column("order_purchase_timestamp", sa.DateTime(), nullable=True),
        sa.Column("order_approved_at", sa.DateTime(), nullable=True),
        sa.Column("order_delivered_carrier_date", sa.DateTime(), nullable=True),
        sa.Column("order_delivered_customer_date", sa.DateTime(), nullable=True),
        sa.Column("order_estimated_delivery_date", sa.DateTime(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "product_category_translation",
        sa.Column("product_category_name", sa.String(), nullable=True),
        sa.Column("product_category_name_english", sa.String(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("product_category_name", sa.String(), nullable=True),
        sa.Column("product_name_lenght", sa.Numeric(), nullable=True),
        sa.Column("product_description_lenght", sa.Numeric(), nullable=True),
        sa.Column("product_photos_qty", sa.Numeric(), nullable=True),
        sa.Column("product_weight_g", sa.Numeric(), nullable=True),
        sa.Column("product_length_cm", sa.Numeric(), nullable=True),
        sa.Column("product_height_cm", sa.Numeric(), nullable=True),
        sa.Column("product_width_cm", sa.Numeric(), nullable=True),
        schema="raw",
    )
    op.create_table(
        "sellers",
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("seller_zip_code_prefix", sa.String(), nullable=True),
        sa.Column("seller_city", sa.String(), nullable=True),
        sa.Column("seller_state", sa.String(), nullable=True),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sellers", schema="raw")
    op.drop_table("products", schema="raw")
    op.drop_table("product_category_translation", schema="raw")
    op.drop_table("orders", schema="raw")
    op.drop_table("order_reviews", schema="raw")
    op.drop_table("order_payments", schema="raw")
    op.drop_table("order_items", schema="raw")
    op.drop_table("geolocation", schema="raw")
    op.drop_table("customers", schema="raw")
    op.drop_index("ix_reviews_review_id", table_name="reviews", schema="curated")
    op.drop_table("reviews", schema="curated")
    op.drop_table("payment_summary", schema="curated")
    op.drop_table("payment_details", schema="curated")
    op.drop_table("order_items", schema="curated")
    op.drop_table("refresh_tokens", schema="curated")
    op.drop_index("ix_orders_status", table_name="orders", schema="curated")
    op.drop_index("ix_orders_purchase_ts", table_name="orders", schema="curated")
    op.drop_index("ix_orders_customer", table_name="orders", schema="curated")
    op.drop_table("orders", schema="curated")
    op.drop_table("users", schema="curated")
    op.drop_table("sellers", schema="curated")
    op.drop_table("products", schema="curated")
    op.drop_table("data_refresh_log", schema="curated")
    op.drop_index("ix_customers_unique_id", table_name="customers", schema="curated")
    op.drop_table("customers", schema="curated")
    op.drop_table("admin_settings", schema="curated")
    # ### end Alembic commands ###
