"""create phase 3 marts

Revision ID: e2e0c9b8f4f2
Revises: 20260805_0001
Create Date: 2026-08-06 09:39:46.580850
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e2e0c9b8f4f2"
down_revision: str | None = "20260805_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    op.execute("CREATE SCHEMA IF NOT EXISTS marts")
    op.execute("CREATE SCHEMA IF NOT EXISTS ml")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_profile",
        sa.Column("customer_unique_id", sa.String(), nullable=False),
        sa.Column("first_order_ts", sa.DateTime(), nullable=True),
        sa.Column("last_order_ts", sa.DateTime(), nullable=True),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("total_spend", sa.Numeric(), nullable=False),
        sa.Column("primary_state", sa.String(length=2), nullable=True),
        sa.Column("primary_city", sa.String(), nullable=True),
        sa.Column("recency_score", sa.SmallInteger(), nullable=False),
        sa.Column("frequency_score", sa.SmallInteger(), nullable=False),
        sa.Column("monetary_score", sa.SmallInteger(), nullable=False),
        sa.Column("rfm_segment", sa.String(), nullable=False),
        sa.Column("clv_historical", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("customer_unique_id"),
        schema="marts",
    )
    op.create_index(
        "ix_customer_profile_region",
        "customer_profile",
        ["primary_state", "primary_city"],
        unique=False,
        schema="marts",
    )
    op.create_index(
        "ix_customer_profile_segment",
        "customer_profile",
        ["rfm_segment"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "customer_segments",
        sa.Column("segment", sa.String(), nullable=False),
        sa.Column("customer_count", sa.Integer(), nullable=False),
        sa.Column("avg_clv", sa.Numeric(), nullable=False),
        sa.Column("avg_order_count", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("segment"),
        schema="marts",
    )
    op.create_table(
        "delivery_performance",
        sa.Column("review_score", sa.SmallInteger(), nullable=True),
        sa.Column("order_status", sa.String(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("delivered_count", sa.Integer(), nullable=False),
        sa.Column("late_count", sa.Integer(), nullable=False),
        sa.Column("avg_delivery_days", sa.Numeric(), nullable=True),
        sa.Column("avg_delivery_delay_days", sa.Numeric(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_delivery_performance_filters",
        "delivery_performance",
        ["date", "state", "category"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "kpi_snapshot",
        sa.Column("snapshot_id", sa.SmallInteger(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("total_revenue", sa.Numeric(), nullable=False),
        sa.Column("total_orders", sa.Integer(), nullable=False),
        sa.Column("total_customers", sa.Integer(), nullable=False),
        sa.Column("average_order_value", sa.Numeric(), nullable=False),
        sa.Column("latest_month_revenue", sa.Numeric(), nullable=False),
        sa.Column("revenue_mom_growth_pct", sa.Numeric(), nullable=True),
        sa.Column("revenue_yoy_growth_pct", sa.Numeric(), nullable=True),
        sa.CheckConstraint("snapshot_id = 1", name="ck_kpi_singleton"),
        sa.PrimaryKeyConstraint("snapshot_id"),
        schema="marts",
    )
    op.create_table(
        "payment_method_mix",
        sa.Column("payment_count", sa.Integer(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("payment_value", sa.Numeric(), nullable=False),
        sa.Column("avg_installments", sa.Numeric(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_payment_mix_filters",
        "payment_method_mix",
        ["payment_type", "date"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "revenue_by_category",
        sa.Column("revenue", sa.Numeric(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("customer_count", sa.Integer(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_revenue_category_filters",
        "revenue_by_category",
        ["category", "date"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "revenue_by_region",
        sa.Column("revenue", sa.Numeric(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("customer_count", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_revenue_region_filters",
        "revenue_by_region",
        ["state", "city", "date"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "revenue_daily",
        sa.Column("revenue", sa.Numeric(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("customer_count", sa.Integer(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_revenue_daily_filters",
        "revenue_daily",
        ["date", "state", "category"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "review_summary",
        sa.Column("review_score", sa.SmallInteger(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("avg_review_score", sa.Numeric(), nullable=False),
        sa.Column("comments_with_text", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_review_summary_filters",
        "review_summary",
        ["date", "category", "seller_id", "review_score"],
        unique=False,
        schema="marts",
    )
    op.create_table(
        "seller_performance",
        sa.Column("revenue", sa.Numeric(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("avg_review_score", sa.Numeric(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("customer_segment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="marts",
    )
    op.create_index(
        "ix_seller_performance_filters",
        "seller_performance",
        ["seller_id", "date"],
        unique=False,
        schema="marts",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_seller_performance_filters", table_name="seller_performance", schema="marts"
    )
    op.drop_table("seller_performance", schema="marts")
    op.drop_index(
        "ix_review_summary_filters", table_name="review_summary", schema="marts"
    )
    op.drop_table("review_summary", schema="marts")
    op.drop_index(
        "ix_revenue_daily_filters", table_name="revenue_daily", schema="marts"
    )
    op.drop_table("revenue_daily", schema="marts")
    op.drop_index(
        "ix_revenue_region_filters", table_name="revenue_by_region", schema="marts"
    )
    op.drop_table("revenue_by_region", schema="marts")
    op.drop_index(
        "ix_revenue_category_filters", table_name="revenue_by_category", schema="marts"
    )
    op.drop_table("revenue_by_category", schema="marts")
    op.drop_index(
        "ix_payment_mix_filters", table_name="payment_method_mix", schema="marts"
    )
    op.drop_table("payment_method_mix", schema="marts")
    op.drop_table("kpi_snapshot", schema="marts")
    op.drop_index(
        "ix_delivery_performance_filters",
        table_name="delivery_performance",
        schema="marts",
    )
    op.drop_table("delivery_performance", schema="marts")
    op.drop_table("customer_segments", schema="marts")
    op.drop_index(
        "ix_customer_profile_segment", table_name="customer_profile", schema="marts"
    )
    op.drop_index(
        "ix_customer_profile_region", table_name="customer_profile", schema="marts"
    )
    op.drop_table("customer_profile", schema="marts")
    # ### end Alembic commands ###
